import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import { NextAppDirEmotionCacheProvider } from "tss-react/next/appDir";
import AppThemeProvider from "@/theme/provider";
import { Header } from "@/components/header";
import Providers from "@/components/providers";
import ClientOnly from "@/components/providers/clientOnly";
import { Toaster } from "react-hot-toast";

export const metadata = {
	title: "An Hung",
	description: "Generated by create next app",
};

const roboto = Roboto({
	weight: ["300", "400", "500", "700"],
	style: ["normal", "italic"],
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head></head>
			<body className={roboto.className}>
				<NextAppDirEmotionCacheProvider options={{ key: "css" }}>
					<AppThemeProvider>
						<Providers>
							<ClientOnly>
								<Header />

								<Toaster />
							</ClientOnly>
							<div
								style={{
									marginTop: "72px",
								}}
							>
								{children}
							</div>
						</Providers>
					</AppThemeProvider>
				</NextAppDirEmotionCacheProvider>
			</body>
		</html>
	);
}
